#!/bin/bash -e

SCRIPT=$(basename ${0})
VERSIONS="9.3 9.4 9.5 9.6 10 11 12 13 14 15 16 17 18"

function help() {
  echo ""
  echo "Script to build tds_fdw RPMs"
  echo ""
  echo "Syntax: "
  echo ""
  echo "${SCRIPT} -p <POSTGRESQL_MAJOR_VERSION>"
  echo ""
  echo "Where: "
  echo "  -p <POSTGRESQL_MAJOR_VERSION> PostgreSQL major version (format X.Y)"
  echo ""
  echo "Supported major versions:"
  for version in ${VERSIONS}; do
    echo "- $version"
  done
  echo ""
  exit 1
}

function print_invalid_syntax() {
  echo "Invalid syntax, use ${SCRIPT} -h"
}

function check_create_dir() {
  if [ ! -d "./$1" ]; then
    mkdir "./$1"
  fi
}

function create_build_env() {
  check_create_dir BUILD
  check_create_dir BUILDROOT
  check_create_dir RPMS
  check_create_dir SOURCES
  check_create_dir SPECS
  check_create_dir SRPMS
}

function get_sources() {
  if [ ! -f "./SOURCES/${2}" ]; then
    echo "Downloading ${1} to "./SOURCES/${2}"..."
    curl -L "${1}" -o "./SOURCES/${2}"
  fi
}

get_url_source_from_spec() {
  local VERSION=$(sed -rn 's/Version:\s*(.*)/\1/p' ${1})
  local URL=$(sed -rn 's/Source:\s*(.*)/\1/p' ${1})
  echo $(echo ${URL}|sed -e "s/%{version}/${VERSION}/g")
}

function build_rpm() {
  rpmbuild --define "_topdir `pwd`" -ba "${1}"
  return ${?}
}

# Parse options
while getopts "p:h" opts; do
  case "${opts}" in
    p) PG_VER=${OPTARG} ;;
    h) help ;;
    *) print_invalid_syntax
       exit 1 ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${PG_VER}" ]; then
  print_invalid_syntax
  exit 1
fi
FOUND='FALSE'
for tver in ${VERSIONS}; do
  if [ "${tver}" == "${PG_VER}" ]; then
    FOUND='TRUE'
  fi
done
if [ "${FOUND}" == 'FALSE' ]; then
  echo "Invalid PostgreSQL major version"
  exit 1
fi

echo "### Creating build environment..."
PG_SVER=$(echo ${PG_VER} | tr -d '.')
SPEC="SPECS/tds_fdw-${PG_SVER}.spec"
URL="$(get_url_source_from_spec ${SPEC})"
TGZ="$(basename ${URL})"

create_build_env
echo "### Downloading sources..."
get_sources ${URL} ${TGZ}
echo "### Building RPMs..."
build_rpm ${SPEC}
if [ $? -eq 0 ]; then
  echo Your packages are available at $PWD/RPMS.
  exit 0
else
  echo There are errors. Check your log.
  exit 2
fi
